nozzle = 0.4;

bridge_length   = 220.0;
bridge_width    = 11.0;
bridge_height   = 25.0;
ramp_length     = 60.0;
deck_thickness  = 2;
pier_offset     = -7.5;
railling_height = 11.0;

top_railling_thickness   = [4 * nozzle, 4 * nozzle];
mid_railling_thickness   = [[.5, nozzle * 2], [.3, nozzle * 2]];
mid_railling_height      = [(6/8), (1.5/8)];
vertical_long_thickness  = [0.7, 3 * nozzle];
vertical_short_thickness = [0.7, 2 * nozzle];
